substitutions:
  bms0: "bms0"
  bms1: "bms1"
  bms2: "bms2"
  bms0_mac_address: A4:C1:37:01:62:8B
  bms1_mac_address: A4:C1:38:E1:D0:0C
  bms2_mac_address: A4:C1:37:32:98:27
  devicename: "Solar Monitor"
esphome:
  name: jbd-bms-ble-mppt
  comment: "Monitor JBD-BMS + Victron MPPT"
  project:
    name: "syssi.esphome-jbd-bms"
    version: 1.5.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: github://syssi/esphome-jbd-bms@main
    refresh: 0s
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s
  - source: github://Fabian-Schmidt/esphome-victron_ble
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Hotspot"
    password: !secret wifi_password

ota:

logger:
  level: error

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 10.1.1.1
      - 0.pool.ntp.org
      - 1.pool.ntp.org

# deep_sleep:
#   id: deep_sleep0
#   run_duration: 3min
#   sleep_duration: 3min


uart:
  - id: uart_0
    baud_rate: 19200
    rx_pin: GPIO18
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     delimiter: "\n"
    #   sequence:
    #     - lambda: UARTDebug::log_string(direction, bytes);
  - id: uart_1
    baud_rate: 19200
    rx_pin: GPIO19
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     delimiter: "\n"
    #   sequence:
    #     - lambda: UARTDebug::log_string(direction, bytes);
  # - id: uart_2
  #   baud_rate: 19200
  #   rx_pin: GPIO21
  #   debug:
  #     direction: BOTH
  #     dummy_receiver: false
  #     after:
  #       delimiter: "\n"
  #     sequence:
  #       - lambda: UARTDebug::log_string(direction, bytes);

victron:
  - uart_id: uart_0
    id: victron0
    throttle: 15s
  - uart_id: uart_1
    id: victron1
    throttle: 15s


# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client
#   topic_prefix: bms
#   discovery_object_id_generator: device_name

api:
  reboot_timeout: 10min

mdns:

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("xiaoxiang", 0) == 0) {
            ESP_LOGI("ble_adv", "New JBD-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${bms0_mac_address}
    id: client0
  - mac_address: ${bms1_mac_address}
    id: client1
  - mac_address: ${bms2_mac_address}
    id: client2

victron_ble:
  - id: charger3
    mac_address: "fd4614c6f313"
    bindkey: "88356df40ca169ace8f5cb4b9d2f111c"


jbd_bms_ble:
  - id: bms0
    ble_client_id: client0
    update_interval: 10s

  - id: bms1
    ble_client_id: client1
    update_interval: 10s

  - id: bms2
    ble_client_id: client2
    update_interval: 10s


binary_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    balancing:
      name: "${bms0} balancing"
    online_status:
      name: "${bms0} online status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    balancing:
      name: "${bms1} balancing"
    online_status:
      name: "${bms1} online status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms2
    balancing:
      name: "${bms2} balancing"
    online_status:
      name: "${bms2} online status"

  - platform: victron_ble
    victron_ble_id: charger3
    device_fault:
      name: "MPPT has Fault"
      type: DEVICE_STATE_FAULT
    charger_error:
      name: "MPPT has Error"
      type: CHARGER_ERROR

sensor:
  - platform: victron
    victron_id: victron0
    max_power_today:
      name: "victron0 Max power today"
      unit_of_measurement: W
      device_class: power
      accuracy_decimals: 2
      state_class: total_increasing
    yield_today:
      name: "victron0 Yield today"
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 2
    yield_yesterday:
      name: "victron0 Yield Yesterday"
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 2
    panel_voltage:
      name: "victron0 panel voltage"
      unit_of_measurement: V
      device_class: voltage
    panel_power:
      name: "victron0 PV power"
      unit_of_measurement: W
      device_class: power
    battery_current:
      name: "victron0 PV current"
      unit_of_measurement: A
      device_class: current
    load_current:
      name: "victron0 load current"
      unit_of_measurement: A
    battery_voltage:
      name: "victron0 Battery voltage"
      unit_of_measurement: V
      device_class: voltage

  - platform: victron
    victron_id: victron1
    max_power_today:
      name: "victron1 Max power today"
      unit_of_measurement: W
      device_class: power
      accuracy_decimals: 2
      state_class: total_increasing
    yield_today:
      name: "victron1 Yield today"
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      accuracy_decimals: 2
    panel_voltage:
      name: "victron1 panel voltage"
      unit_of_measurement: V
      device_class: voltage
    panel_power:
      name: "victron1 PV power"
      unit_of_measurement: W
      device_class: power
    battery_current:
      name: "victron1 PV current"
      unit_of_measurement: A
      device_class: current
    load_current:
      name: "victron1 load current"
      unit_of_measurement: A
      device_class: current
    battery_voltage:
      name: "victron1 Battery voltage"
      unit_of_measurement: V
      device_class: voltage


  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 Battery Voltage"
    type: BATTERY_VOLTAGE
    unit_of_measurement: V
    device_class: voltage
  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 Battery Current"
    type: BATTERY_CURRENT
    unit_of_measurement: A
    device_class: current
  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 Yield Today"
    type: YIELD_TODAY
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 PV Power"
    type: PV_POWER
    device_class: power
    unit_of_measurement: W
  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 Load Current"
    type: LOAD_CURRENT
    unit_of_measurement: A
    device_class: current

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    charging_power:
      id: bms0_charging_power
      name: "${bms0} charging power"
      device_class: power
      unit_of_measurement: W
    discharging_power:
      id: bms0_discharging_power
      name: "${bms0} discharging power"
      device_class: power
      unit_of_measurement: W
    state_of_charge:
      name: "${bms0} state of charge"
      device_class: battery
    capacity_remaining:
      id: bms0_capacity_remaining
      name: "${bms0} capacity remaining"
      device_class: energy_storage
      unit_of_measurement: Ah
    total_voltage:
      name: "${bms0} total voltage"
      id: bms0_total_voltage
      device_class: voltage
    average_cell_voltage:
      name: "${bms0} average cell voltage"
      id: bms0_average_cell_voltage
      device_class: voltage
    delta_cell_voltage:
      name: "${bms0} delta cell voltage"
    temperature_1:
      name: "${bms0} temperature 1"
      device_class: temperature
    temperature_2:
      name: "${bms0} temperature 2"
      device_class: temperature
    temperature_3:
      name: "${bms0} temperature 3"
      device_class: temperature


  - platform: total_daily_energy
    name: "${bms0} energy stored"
    power_id: bms0_charging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
  - platform: total_daily_energy
    name: "${bms0} energy consumed"
    power_id: bms0_discharging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    charging_power:
      name: "${bms1} charging power"
      id: bms1_charging_power
      device_class: power
    discharging_power:
      name: "${bms1} discharging power"
      id: bms1_discharging_power
      device_class: power
    state_of_charge:
      name: "${bms1} state of charge"
      device_class: battery
    capacity_remaining:
      name: "${bms1} capacity remaining"
      device_class: energy_storage
      unit_of_measurement: Ah
    total_voltage:
      name: "${bms1} total voltage"
      device_class: voltage
    average_cell_voltage:
      name: "${bms1} average cell voltage"
      device_class: voltage
    delta_cell_voltage:
      device_class: voltage
      name: "${bms1} delta cell voltage"
    temperature_1:
      name: "${bms1} temperature 1"
    temperature_2:
      name: "${bms1} temperature 2"

  - platform: total_daily_energy
    name: "${bms1} energy stored"
    power_id: bms1_charging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "${bms1} energy consumed"
    power_id: bms1_discharging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001


  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms2
    charging_power:
      name: "${bms2} charging power"
      id: bms2_charging_power
      device_class: power
    discharging_power:
      name: "${bms2} discharging power"
      id: bms2_discharging_power
      device_class: power
    state_of_charge:
      name: "${bms2} state of charge"
      device_class: battery
    capacity_remaining:
      name: "${bms2} capacity remaining"
      device_class: energy_storage
      unit_of_measurement: Ah
    total_voltage:
      name: "${bms2} total voltage"
      device_class: voltage
    average_cell_voltage:
      name: "${bms2} average cell voltage"
      device_class: voltage
    delta_cell_voltage:
      device_class: voltage
      name: "${bms2} delta cell voltage"
    temperature_1:
      name: "${bms2} temperature 1"
    temperature_2:
      name: "${bms2} temperature 2"

  - platform: total_daily_energy
    name: "${bms2} energy stored"
    power_id: bms2_charging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: total_daily_energy
    name: "${bms2} energy consumed"
    power_id: bms2_discharging_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001


text_sensor:


  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    errors:
      name: "${bms0} errors"
    operation_status:
      name: "${bms0} operation status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    errors:
      name: "${bms1} errors"
    operation_status:
      name: "${bms1} operation status"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms2
    errors:
      name: "${bms2} errors"
    operation_status:
      name: "${bms2} operation status"

  - platform: victron
    victron_id: victron0
    firmware_version:
      name: "victron0 firmware version"
    device_type:
      name: "victron0 device type"
    serial_number:
      name: "victron0 serial number"
    charging_mode:
      name: "victron0 charging mode"
    error:
      name: "victron0 error"

  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 MPPT state"
    type: DEVICE_STATE
  - platform: victron_ble
    victron_ble_id: charger3
    name: "victron3 error"
    type: CHARGER_ERROR


switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${bms0} enable bluetooth connection"

  - platform: ble_client
    ble_client_id: client1
    name: "${bms1} enable bluetooth connection"

  - platform: ble_client
    ble_client_id: client2
    name: "${bms2} enable bluetooth connection"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms0
    charging:
      name: "${bms0} charging"
    discharging:
      name: "${bms0} discharging"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms1
    charging:
      name: "${bms1} charging"
    discharging:
      name: "${bms1} discharging"

  - platform: jbd_bms_ble
    jbd_bms_ble_id: bms2
    charging:
      name: "${bms2} charging"
    discharging:
      name: "${bms2} discharging"

