substitutions:
  devicename: "solarmonitor"

esphome:
  name: jbd-bms-ble-mppt
  comment: "Monitor JBD-BMS + Victron MPPT"
  project:
    name: "syssi.esphome-jbd-bms"
    version: 1.5.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
preferences:
  flash_write_interval: 30min

external_components:
  - source: github://syssi/esphome-jbd-bms@main
    refresh: 0s
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s
  - source: github://Fabian-Schmidt/esphome-victron_ble
    refresh: 0s

<<: !include wifi.yaml
<<: !include common.yaml

# deep_sleep:
#   id: deep_sleep0
#   run_duration: 3min
#   sleep_duration: 3min

esp32_ble_tracker:

uart:
  - id: uart_0
    baud_rate: 19200
    rx_pin: GPIO18

  - id: uart_1
    baud_rate: 19200
    rx_pin: GPIO19

  # - id: uart_2
  #   baud_rate: 19200
  #   rx_pin: GPIO21


packages:
  charger0: !include
    file: charger.yaml
    vars:
      victron_id: charger0
      mac_address: "fdc923f1e120"
      bindkey: "1a4556bc22ae31112c6193d81660709e"

  charger1: !include
    file: charger.yaml
    vars:
      victron_id: charger1
      mac_address: "e3bbba57b89d"
      bindkey: "9a4825845cf53e74484af66800026083"

  charger2: !include
    file: charger.yaml
    vars:
      victron_id: charger2
      mac_address: "fd4614c6f313"
      bindkey: "88356df40ca169ace8f5cb4b9d2f111c"

  bms0: !include
    file: bms.yaml
    vars:
      bms_id: bms0
      bms_mac_address: "A4:C1:37:01:62:8B"

  bms1: !include
    file: bms.yaml
    vars:
      bms_id: bms1
      bms_mac_address: "A4:C1:38:E1:D0:0C"

  bms2: !include
    file: bms.yaml
    vars:
      bms_id: bms2
      bms_mac_address: "A4:C1:37:32:98:27"

  # bms3: !include
  #   file: bms.yaml
  #   vars:
  #     bms_id: bms3
  #     bms_mac_address: "A4:C1:37:22:97:3B"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: htu21d
    update_interval: 60s
    temperature:
      id: temperature
      name: "Temperature (Si7021)"
      filters:
      - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      id: humidity
      name: "Humidity (Si7021)"
      device_class: humidity
