substitutions:
  device_name: "bms-node"

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
#  includes: bms.h

esp32:
  board: esp32-evb
  framework:
    type: esp-idf

<<: !include common.yaml





ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
  manual_ip:
    static_ip: 10.1.1.162
    gateway: 10.1.1.1
    subnet: 255.255.255.0
  domain: .lan


esp32_ble_tracker:

# deep_sleep:
#   run_duration: 60s
#   sleep_duration: 30s

uart:
  - id: uart_1
    baud_rate: 2400
    rx_pin: GPIO36
    tx_pin: GPIO4


packages:

  charger2: !include
    file: charger.yaml
    vars:
      victron_id: charger2
      mac_address: "fd4614c6f313"
      bindkey: !secret charger2_bindkey

  # bms0: !include
  #   file: bms.yaml
  #   vars:
  #     bms_id: bms0
  #     bms_mac_address: "A4:C1:37:01:62:8B"

  # bms1: !include
  #   file: bms.yaml
  #   vars:
  #     bms_id: bms1
  #     bms_mac_address: "A4:C1:38:E1:D0:0C"
  #     update_interval: 30s

  bms2: !include
    file: bms.yaml
    vars:
      bms_id: bms2
      bms_mac_address: "A4:C1:37:32:98:27"
      update_interval: 15s

  bms3: !include
    file: bms.yaml
    vars:
      bms_id: bms3
      bms_mac_address: "A4:C1:37:22:97:3B"
      update_interval: 15s

  inverter1: !include
    file: pipsolar.yaml
    vars:
      inverter_id: inverter0
      inverter_name: "Inverter0"
      uart_id: uart_1

i2c:
  sda: 13
  scl: 16
  scan: true

sensor:
  - platform: mcp9808
    id: outside_temperature
    name: "Outside Temperature"
    update_interval: 60s
    on_value_range:
    - below: 33.0
      then:
        - script.execute:
            id: bms2_disable_charging_script
            reason: "Too cold"
        - script.execute:
            id: bms3_disable_charging_script
            reason: "Too cold"
    - above: 34.5
      then:
        - script.execute: bms2_enable_charging_script
        - script.execute: bms3_enable_charging_script

