
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Hotspot"
    password: !secret wifi_password

ota:
mdns:
logger:
  level: INFO
  hardware_uart: UART0
#  baud_rate: 0

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 10.1.1.1
      - 0.pool.ntp.org
      - 1.pool.ntp.org
api:
  reboot_timeout: 10min

preferences:
  flash_write_interval: 60min
