substitutions:
  devicename: "esphome-display"

esphome:
  name: esp32-m5stack-lcd
  # libraries:
  #   - "display"
  includes:
    - widget.h
    #- src/esphome/components/light/esp_hsv_color.h
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 240000000L
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
    board_upload.flash_size: 4MB

esp32:
  board: m5stack-grey
  framework:
    type: esp-idf

psram:
  speed: 40Mhz

<<: !include common.yaml


light:

spi:
  clk_pin: 18
  mosi_pin: 23
  # miso_pin: 25

i2c:
  sda: 21
  scl: 22

<<: !include display.yaml
<<: !include sensors.yaml
