sensor:
  - platform: homeassistant
    name: "BMS0 SOC"
    id: battery_0_level
    entity_id: sensor.bms0_soc
    unit_of_measurement: "%"
    internal: true
  - platform: homeassistant
    name: "BMS1 SOC"
    id: battery_1_level
    entity_id: sensor.bms1_soc
    unit_of_measurement: "%"
    internal: true
  - platform: homeassistant
    name: "BMS2 SOC"
    id: battery_2_level
    entity_id: sensor.bms2_soc
    unit_of_measurement: "%"
    internal: true
  - platform: homeassistant
    name: "BMS3 SOC"
    id: battery_3_level
    entity_id: sensor.bms3_soc
    unit_of_measurement: "%"
    internal: true
  - platform: homeassistant
    id: nws_temperature
    entity_id: weather.kbbg_daynight
    attribute: temperature
    unit_of_measurement: "°F"
    internal: true
  - platform: homeassistant
    name: "PV0"
    id: pv_power_0
    entity_id: sensor.charger0_pv_power
    unit_of_measurement: "W"
    internal: true
    accuracy_decimals: 2
    filters:
      - heartbeat: 10s
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
          send_first_at: 1
  - platform: homeassistant
    name: "PV1"
    id: pv_power_1
    entity_id: sensor.charger1_pv_power
    unit_of_measurement: "W"
    internal: true
    accuracy_decimals: 2
    filters:
      - heartbeat: 10s
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
          send_first_at: 1
  - platform: homeassistant
    name: "PV3"
    id: pv_power_2
    entity_id: sensor.charger2_pv_power
    unit_of_measurement: "W"
    internal: true
    accuracy_decimals: 2
    filters:
      - heartbeat: 10s
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
          send_first_at: 1
  - platform: homeassistant
    id: pv_yield_0
    entity_id: sensor.charger0_yield_today
    unit_of_measurement: "kWh"
    internal: true
    name: "Yield0"
  - platform: homeassistant
    id: pv_yield_1
    entity_id: sensor.charger1_yield_today
    unit_of_measurement: "kWh"
    internal: true
    name: "Yield1"
  - platform: homeassistant
    id: pv_yield_2
    entity_id: sensor.charger2_yield_today
    unit_of_measurement: "kWh"
    internal: true
    name: "Yield2"
